### ISSUE TITLE
getBiomeColor()

### ISSUE THREAD

**Issue by YaBoiSavion** [H4PM/Elywing#246]
when i start the server on my local host(laptop) it does this

15:54:54 | Elywing thread:CRITICAL > Error: "Call to undefined method pocketmine\level\format\generic\GenericChunk::getBiomeColor()" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2732

the server doesnt crash though

**Comment by ParkChanSol** [comment]
and CrashDump
[CrashDump_Sat_Dec_31-23.25.43-AWST_2016.txt](https://github.com/H4PM/Elywing/files/679886/CrashDump_Sat_Dec_31-23.25.43-AWST_2016.txt)
Elywing Crash Dump Sat Dec 31 23:25:43 AWST 2016

Error: Call to undefined method pocketmine\level\format\generic\GenericChunk::getBiomeColor()
File: /src/pocketmine/level/Level
Line: 2732
Type: notice

Code:
[2723] 		$chunk = $this->provider->getChunk($x, $z, $generate);
[2724] 		if($chunk === null){
[2725] 			if($generate){
[2726] 				throw new \InvalidStateException("Could not create new Chunk");
[2727] 			}
[2728] 			return false;
[2729] 		}
[2730] 
[2731] 		if($this->provider->getProviderName() == "mcregion"){
[2732] 			if($chunk->getBiomeColor(0, 0) == [0, 0, 0]){
[2733] 				for($x = 0; $x < 16; ++$x){
[2734] 					for($z = 0; $z < 16; ++$z){
[2735] 						$biome = Biome::getBiome(Biome::PLAINS);
[2736] 						$chunk->setBiomeId($x, $z, $biome->getId());
[2737] 						$c = $biome->getColor();
[2738] 						$chunk->setBiomeColor($x, $z, $c >> 16, ($c >> 8) & 0xff, $c & 0xff);
[2739] 					}
[2740] 				}
[2741] 			}
[2742] 		}

Backtrace:
#0 /src/pocketmine/level/Level(2998): pocketmine\level\Level->getChunk(integer 16, integer 16, boolean 1)
#1 /src/pocketmine/Server(1266): pocketmine\level\Level->populateChunk(integer 16, integer 16, boolean 1)
#2 /src/pocketmine/Server(1968): pocketmine\Server->generateLevel(string nether, integer 1483197943, string pocketmine\level\generator\hell\Nether)
#3 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Downloads\LEO_ONLINE\, string C:\Users\Administrator\Downloads\LEO_ONLINE\, string C:\Users\Administrator\Downloads\LEO_ONLINE\plugins\, string unknown)

Genisys version: 8f465763c590293e2003ce616832b6507edf5b1c [Protocol 100; API 3.0.0-ALPHA1]
uname -a: Windows NT MSDN-SPECIAL 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
PHP version: 7.0.13
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 4 초
Number of loaded worlds: 3
Players online: 0/20

Loaded plugins:
DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
PluginForceLoader 빌드1 by solo for API(s) 2.0.0, 2.1.0, 3.0.0, 3.0.0-ALPHA1
GoogleGlass 1.1 by JacobYun for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0

**Comment by Muqsit** [comment]
Do any of your plugins use getBiomeColor()? That was removed because you can't change biome color in mcpe1.0

**Comment by Driesboy** [comment]
plugins like MYPLOT need to be updated

**Comment by Tolo0** [comment]
I'm getting this same error.  i cant figure out why

**Comment by Infernus102** [comment]
Tolo you use myplot

**Comment by Infernus102** [comment]
Fixed, check my pr

**Comment by Tolo0** [comment]
no I deleted myplot but same error

**Comment by Infernus102** [comment]
Check pull request

**Comment by Tolo0** [comment]
new error. 

Elywing thread:DEBUG > BatchPacket  0x
19:54:39 | Elywing thread:CRITICAL > InvalidArgumentException: "BatchPacket payload is empty or packet decode error" (EXCEPTION) in "/src/pocketmine/network/Network" at line 233
19:54:39 | Elywing thread:DEBUG > #0 /src/pocketmine/network/RakLibInterface(141): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
19:54:39 | Elywing thread:DEBUG > #1 /src/raklib/server/ServerHandler(99): pocketmine\network\RakLibInterface->handleEncapsulated(string 81.219.203.228:19132, raklib\protocol\EncapsulatedPacket .2......Nx..C......?....Q...6x...........r..8....6..]...Ta.*...........<k^%.n;..H.M.)..u......>.P.,.....~...q.....?.;3O....SC=.C.8....y...x#.3.....R....P...Z.zWs..x.%....ie*.6..........I.Ux..M#EDv...F..xG.....=...9#.%..[*Y...9.\.>...............7._.is.....y..........K.."!.@...4..r...N.N.XIy..w.;.....=.z9.(.R.l.t......F.....]].":.t.*..).5.o.#y.....6..USW$..8tE...D.9T*.......2...u._.._...p...EB..@..5..k.9....=.....r.qx...J...l6'.......Xs.4].^;..'.=.....G.J#...5f..LM...V..h..V..J...8...S.%[.G[q......J$.=,k..s...8.......r+..K.:.....V......D....Dp.Y......V..~.!.....<a.......)....1..............{.|~..)8-..60..b:b.....*../.M:}.%...'.s....Ox.J8....3<t3i.z.t'h.....Q... ..(.-BX<C$.....J..e..4....._.......O.....d.zQ V...D6&....G.(..*.<.,'._Q..`..N..N+."s.NG.2n.h4.....4...M.>...T ..M*7.t....A...b.X,...b}O.T.B..9....I....;./...5Z...=.:E.t..B...5R.,4ZTa....[.+.....N[...Q.".%........'.E..%..].MO.G..o..w..^....~|z.......-a~....g..8...........u.........././k.:".{.....W.......eF7?[........o.{.#7........?..r..o..zU.?....c.7......_...........|....'......7?..Nv.'.%..x[.....o0m..?[=.#.56..>......O..[.....u..W....{.K.@B...Xu........_..{..~.H..X.u.....z.|=....>.{.;..\._..........W]..f.G.V..x.....b~,.w.1.a......v.o.1.a......v.o.1.a......v.o.1.a......v.o.1.a......v.o(.......I......")$..~.xqH..P.T......-\2......S..S....a~....g.Fg.Q..Z....zz&.......=..b......Xq...Mly..?=......e>Z..#h...U..)..-.c1..s....:..o..-.o...3.a.*/...t.....s.....z..o.y....V...=...c~.M.e..c.....~.....X,...b.X..*-<..[..8._~3...]~C2..*. ...6.LI^}...........P..tvz..n.&.....Q.."j...G..nB.....h..u..K.i..[J.....3v[...F}...}..M~.Nb.{....N..X7.fb.....wJ...Q.L., integer 0)
19:54:39 | Elywing thread:DEBUG > #2 /src/pocketmine/network/RakLibInterface(76): raklib\server\ServerHandler->handlePacket(boolean)
19:54:39 | Elywing thread:DEBUG > #3 /src/pocketmine/network/Network(159): pocketmine\network\RakLibInterface->process(boolean)
19:54:39 | Elywing thread:DEBUG > #4 /src/pocketmine/Server(2823): pocketmine\network\Network->processInterfaces(boolean)
19:54:39 | Elywing thread:DEBUG > #5 /src/pocketmine/Server(2523): pocketmine\Server->tick(boolean)
19:54:39 | Elywing thread:DEBUG > #6 /src/pocketmine/Server(2401): pocketmine\Server->tickProcessor(boolean)
19:54:39 | Elywing thread:DEBUG > #7 /src/pocketmine/Server(1991): pocketmine\Server->start(boolean)
19:54:39 | Elywing thread:DEBUG > #8 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/tolo/mc2/, string /home/tolo/mc2/, string /home/tolo/mc2/plugins/, string unknown)
19:54:46 | Elywing thread:DEBUG > Attempted to drop a null crafting inventory

19:54:46 | Elywing thread:INFO > [/81.219.203.228:19132] logged out due to client disconnect
19:54:58 | Elywing thread:DEBUG > Attempted to drop a null crafting inventory

19:54:58 | Elywing thread:INFO > [/82.149.190.199:19132] logged out due to Login timeout

**Comment by Infernus102** [comment]
Startup error?

**Comment by alexbgameson** [comment]
This error has been fixed in the ClearSky Team fork of Elywing. 
https://drive.google.com/open?id=0BwqaBULNj-MJdnQ4ZkZwZEVxOGc

**Comment by andris155** [comment]
@alexbgameson  new error 02.01 00:00:34 [Server] CRITICAL Error: "Call to undefined method pocketmine\level\Level::getWeather()" (EXCEPTION) in "/src/pocketmine/Player" at line 1059

**Comment by andris155** [comment]
@alexbgameson thx.

**Comment by Iktaniyalol** [comment]
We need update Myplot...
